# Shared settings between local deployments. Use this to mock out secret
# credentials in dev and testing.
local: &local
  aws_access_key_id: AKIANOTAREALKEY
  aws_secret_access_key: <%= SecureRandom.hex.to_s %>
  aws_cloudfront_distribution_id: 12345678
  aws_s3_bucket_name: bucket
  podcast_file_name: podcast.xml

development: &local
  secret_key_base: 40fd04d64279228409e34cb023f47e3f87bd3d97411f435576462dce083f7f3834d5926e1f2572806c1b82329170297d15d7c3143dd8153b8cc8ee2a56856bf2

test: &local
  secret_key_base: 51389ab6df237c663565770476f10f8aba186893272c70a6e4aa4b4265e67767afd4ed15a89140a4a4ee52a8b742f6f24569ca77b1f5f5a58d6d2c16913d4375

# Store all secret credentials in environment configuration, but use the
# Rails secrets engine to communicate to the app.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_cloudfront_distribution_id: <%= ENV['AWS_CLOUDFRONT_DISTRIBUTION_ID'] %>
  aws_s3_bucket_name: <%= ENV['AWS_S3_BUCKET_NAME'] %>
  podcast_file_name: <%= ENV['PODCAST_FILE_NAME'] %>
